<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>RBX_Alt_Manager</RootNamespace>
    <AssemblyName>NTG Manager</AssemblyName>
    <ApplicationIcon>Resources\team_KX4_icon.ico</ApplicationIcon>
    <ApplicationManifest>app1.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Newtonsoft.Json.Schema" Version="3.0.15" />
    <PackageReference Include="RestSharp" Version="110.2.0" />
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="ObjectListView.Official" Version="2.9.1" ExcludeAssets="build" />
    <PackageReference Include="FCTB" Version="2.16.24" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="libsodium-net" Version="0.10.0" ExcludeAssets="build" />
    <PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1" />
    <PackageReference Include="Yove.Proxy" Version="1.1.1" />
    <PackageReference Include="Esendex.TokenBucket" Version="1.0.7" />
    <PackageReference Include="CefSharp.WinForms.NETCore" Version="117.2.20" />
    <PackageReference Include="PuppeteerSharp" Version="10.0.0" />
    <PackageReference Include="PuppeteerExtraSharp" Version="2.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomResourceLogicalName>RBX_Alt_Manager.Properties.Resources.resources</CustomResourceLogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>